### ISSUE TITLE
Create new dinners

### ISSUE THREAD

**Issue by aslakhol** [aslakhol/sulten#6]
I imagine that clicking the [+] would open a box that kinda looks like the dinner boxes, but with an input field for the name, a save button on the right side, and a combobox for selecting and making tags.

**Comment by aslakhol** [comment]
Maybe the save button is under the box, so that there is more room.

**Comment by aslakhol** [comment]
<img width="758" alt="image" src="https://github.com/aslakhol/sulten/assets/11901064/87cee769-8d3e-4a2d-a9e6-7418f6d37273">

**Comment by Madelelo** [comment]
Done
