### ISSUE TITLE
Add tags to dinners

### ISSUE THREAD

**Issue by aslakhol** [aslakhol/sulten#7]
I imagine a green + box in the style of the tags, at the end of the list of the tags. When hit it would open the combobox for adding new tags.

**Comment by aslakhol** [comment]
Maybe adding tags is just editing dinner? So that you can change the title and remove tags as well.

**Comment by aslakhol** [comment]
<img width="758" alt="image" src="https://github.com/aslakhol/sulten/assets/11901064/a9be9aba-a833-4889-8b3a-6e509aa9b0ff">

**Comment by Madelelo** [comment]
Done in 5cc4a84
